services:
  - type: web
    name: etsy-customizer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGIN
        value: https://YOUR_FRONTEND_HOST
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false

